name = "mc mods"
author = "Mohammed Albarq"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41b04620f78de39c4efd71c20211c68b5b31ec289bfc7cd9c54a3ec7153aad3a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
