name = "mc mods"
author = "Mohammed Albarq"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "681ba6f4ef95def18f0af990c9f3d781f13dcdae32345e8d15c7dc6416c7c326"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
