name = "mc mods"
author = "Mohammed Albarq"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f46fd10a8cca6aa2cd849f6239729a6b24c38f27c81bc4c5626acf9ab0e88e5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
